# Generated by Django 3.0.7 on 2020-06-26 15:59

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),                
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=150)),
                ('caste', models.CharField(max_length=150)),
                ('community', models.CharField(max_length=150)),
                ('religion', models.CharField(max_length=150)),
                ('mail_id', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('aadhar_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('date_of_joining', models.DateField()),
                ('course', models.CharField(max_length=250)),
                ('student_photo', models.ImageField(upload_to='')),
                ('family_photo', models.ImageField(upload_to='')),
                ('father_name', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('father_occupation', models.CharField(max_length=250)),
                ('mother_occupation', models.CharField(max_length=250)),
                ('parent_phone_number', models.CharField(max_length=20)),
                ('parent_annual_income', models.IntegerField()),
                ('bank_name', models.CharField(max_length=250)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('language_subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('language_marks', models.FloatField(blank=True, null=True)),
                ('english_subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('english_marks', models.FloatField(blank=True, null=True)),
                ('major_subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('major_marks', models.FloatField(blank=True, null=True)),
                ('allied_subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('allied_marks', models.FloatField(blank=True, null=True)),
                ('elective_subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('elective_marks', models.FloatField(blank=True, null=True)),
                ('major_practical_subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('major_practical_marks', models.FloatField(blank=True, null=True)),
                ('allied_practical_subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('allied_practical_marks', models.FloatField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.studentdetails')),
            ],
        ),
    ]
